import { vi } from 'vitest';
import type { BroadcastInboxStrings } from './types';
import type { ChatBroadcast } from '../ConversationThread/types';

// Shared fixtures for the BroadcastInbox test files.
export const strings: BroadcastInboxStrings = {
  placeholder: 'Type a message…',
  send: 'Send',
  readTooltipRead: 'Read',
  readTooltipUnread: 'Not read yet',
  loadError: 'Could not load messages.',
  sendError: 'Could not send. Try again.',
  sentTabLabel: 'Sent',
  receivedTabLabel: 'Received',
  newMessageLabel: 'New Message',
  unreadOnlyLabel: (n) => `Unread (${n})`,
  noSentYet: "You haven't sent any messages yet.",
  noReceivedYet: 'Nothing sent to you yet.',
  nothingUnread: 'Nothing unread.',
  sentByYou: 'Sent by you',
  sentBy: (name) => `Sent by ${name}`,
  sentBySomeoneElse: 'Someone else',
  notOpened: 'Not opened',
  readNoReply: 'Read, no reply',
  replied: 'Replied',
  repliedOn: (date) => `Replied ${date}`,
  allAnswered: 'All answered',
  waitingOn: (n) => `Waiting on ${n}`,
  needsReplyCount: (n) => `${n} need a reply`,
  closedLabel: 'Closed',
  withdrawnLabel: 'Withdrawn',
  waitingOnYou: 'Waiting on you',
  answeredLabel: 'Answered',
  deleteConversation: 'Delete conversation',
  deleteConfirmTitle: 'Delete this conversation?',
  deleteConfirmBody: (title) => `Permanently delete "${title}"?`,
  deleteLabel: 'Delete',
  cancelLabel: 'Cancel',
  closeConversationLabel: 'Close conversation',
  stopAskingLabel: 'Stop asking',
  everyoneAnswered: 'Everyone has answered.',
  onePersonWaiting: '1 person still owes a reply.',
  peopleWaiting: (n) => `${n} people still owe a reply.`,
  loadingLabel: 'Loading…',
  searchLabel: 'Search',
  searchPlaceholder: 'Subject or person…',
  statusFilterLabel: 'Status',
  statusAllLabel: 'All statuses',
  statusNeedsReplyLabel: 'Needs reply',
  statusWaitingLabel: 'Waiting',
  statusAnsweredLabel: 'Answered',
  statusClosedLabel: 'Closed',
  dateFromLabel: 'From',
  dateToLabel: 'To',
  personFilterLabel: 'Person',
  personFilterPlaceholder: 'Type a name…',
  clearFiltersLabel: 'Clear filters',
  noResultsLabel: 'No conversations match these filters.',
  backToMessagesLabel: 'Back to messages',
  notFoundLabel: 'This conversation is no longer available.',
};

export function broadcast(overrides: Partial<ChatBroadcast> = {}): ChatBroadcast {
  return {
    id: 'b1',
    title: 'Confirm your hours',
    body: 'Please confirm your hours.',
    createdAt: new Date().toISOString(),
    closedAt: null,
    createdBy: 'admin-1',
    senderName: 'Dev Admin',
    requiresReply: true,
    messages: [],
    recipients: [{ participant: { id: 'worker-1', name: 'Carlos Vidana' }, respondedAt: null, openedAt: null }],
    unread: false,
    ...overrides,
  };
}

export const baseProps = {
  fetchReceived: async () => [] as ChatBroadcast[],
  onSendMessage: vi.fn(),
  onMarkRead: vi.fn(),
  onClose: vi.fn(),
  onDelete: vi.fn(),
  onOpen: vi.fn(),
  strings,
};

