import type { ReactNode } from 'react';
import storyOrder from '../generated/storyOrder.json';
import storySource from '../generated/storySource.json';

// Renders a real named export from an existing *.stories.tsx file, so demos
// never have to be re-authored: every story already IS a working example,
// picked to demonstrate this exact component.
type Decorator = (story: () => ReactNode, context: { args: Record<string, unknown> }) => ReactNode;
// Loosely typed on purpose: these describe the shape of real
// @storybook/react CSF exports (Meta/StoryObj), which this file deliberately
// avoids depending on directly - `decorators` in particular is typed by
// Storybook as "one decorator or an array of them", not worth re-deriving.
type Meta = { component?: React.ComponentType<any>; args?: Record<string, unknown>; decorators?: any; title?: string };
type Story = { args?: Record<string, unknown>; render?: (args: any) => ReactNode; decorators?: any };

function asArray(decorators: any): Decorator[] {
  if (!decorators) return [];
  return Array.isArray(decorators) ? decorators : [decorators];
}

export function renderStory(meta: Meta, story: Story): ReactNode {
  const args = { ...meta.args, ...story.args };
  const Component = meta.component!;
  let render: () => ReactNode = () => (story.render ? story.render(args) : <Component {...args} />);
  // Story-level decorators wrap first (innermost), meta-level wrap outside
  // them - matches Storybook's own composition order closely enough for a
  // static preview (global-level decorators don't apply here, none used).
  for (const decorator of [...asArray(story.decorators), ...asArray(meta.decorators)]) {
    const inner = render;
    render = () => decorator(inner, { args });
  }
  return render();
}

// Every named export except `default` (the meta) is a story - so a whole
// component's demos come from one import, no story names to keep in sync.
//
// A module namespace object lists its exports ALPHABETICALLY (an ECMAScript
// spec quirk, confirmed live: ColorField's Object.keys comes back as
// ['Blue', 'Red', 'default'], not source order) - so left alone, every
// demo across the whole catalog would silently render in alphabetical
// rather than authored order. `storyOrder.json` (generated by scanning each
// *.stories.tsx file's actual text - see scripts/generate-props.mjs) restores
// the real declaration order, keyed off `meta.title`'s "Components/Name".
export function demosFromModule(mod: Record<string, any>): { label: string; node: ReactNode; code?: string }[] {
  const meta = mod.default as Meta;
  const labels = Object.keys(mod).filter(key => key !== 'default');

  const componentName = meta.title?.replace(/^Components\//, '');
  const order = componentName ? (storyOrder as Record<string, string[]>)[componentName] : undefined;
  if (order) {
    labels.sort((a, b) => order.indexOf(a) - order.indexOf(b));
  }

  const sources = componentName ? (storySource as Record<string, Record<string, string>>)[componentName] : undefined;
  return labels.map(label => ({
    label,
    node: renderStory(meta, mod[label] as Story),
    code: sources?.[label],
  }));
}
